# Generated by Django 5.2.1 on 2025-05-28 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='テンプレート名')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'シフトテンプレート',
                'verbose_name_plural': 'シフトテンプレート',
            },
        ),
        migrations.CreateModel(
            name='ShiftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='シフト種別名')),
                ('color', models.CharField(default='#3498db', max_length=20, verbose_name='表示色')),
                ('start_time', models.TimeField(verbose_name='デフォルト開始時間')),
                ('end_time', models.TimeField(verbose_name='デフォルト終了時間')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
            ],
            options={
                'verbose_name': 'シフト種別',
                'verbose_name_plural': 'シフト種別',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='電話番号')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='メールアドレス')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='役職/担当')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーアカウント')),
            ],
            options={
                'verbose_name': 'スタッフ',
                'verbose_name_plural': 'スタッフ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShiftTemplateDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, '月曜日'), (1, '火曜日'), (2, '水曜日'), (3, '木曜日'), (4, '金曜日'), (5, '土曜日'), (6, '日曜日')], verbose_name='曜日')),
                ('start_time', models.TimeField(verbose_name='開始時間')),
                ('end_time', models.TimeField(verbose_name='終了時間')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='shift_management.shifttemplate', verbose_name='テンプレート')),
                ('shift_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_management.shifttype', verbose_name='シフト種別')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_management.staff', verbose_name='スタッフ')),
            ],
            options={
                'verbose_name': 'シフトテンプレート詳細',
                'verbose_name_plural': 'シフトテンプレート詳細',
                'unique_together': {('template', 'staff', 'weekday')},
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('start_time', models.TimeField(verbose_name='開始時間')),
                ('end_time', models.TimeField(verbose_name='終了時間')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('shift_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shift_management.shifttype', verbose_name='シフト種別')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_management.staff', verbose_name='スタッフ')),
            ],
            options={
                'verbose_name': 'シフト',
                'verbose_name_plural': 'シフト',
                'ordering': ['date', 'start_time'],
                'unique_together': {('staff', 'date', 'start_time')},
            },
        ),
    ]
