# Generated by Django 5.2.3 on 2025-06-13 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_management', '0004_staff_approval_status_staff_approved_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='approval_status',
            field=models.CharField(choices=[('pending', '承認待ち'), ('approved', '承認済み'), ('rejected', '却下')], default='pending', max_length=20, verbose_name='承認状態'),
        ),
        migrations.AddField(
            model_name='shift',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='承認日時'),
        ),
        migrations.AddField(
            model_name='shift',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_shifts', to=settings.AUTH_USER_MODEL, verbose_name='承認者'),
        ),
        migrations.AddField(
            model_name='shift',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='却下理由'),
        ),
    ]
