# Generated by Django 5.2.3 on 2025-06-13 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_management', '0005_shift_approval_status_shift_approved_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shifts', to=settings.AUTH_USER_MODEL, verbose_name='作成者'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='approval_status',
            field=models.CharField(choices=[('pending', '承認待ち'), ('approved', '承認済み'), ('rejected', '却下')], default='approved', max_length=20, verbose_name='承認状態'),
        ),
    ]
