# Generated by Django 5.2.3 on 2025-06-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_management', '0006_shift_created_by_alter_shift_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='role_type',
            field=models.CharField(choices=[('user', '利用者'), ('part_time', 'アルバイト'), ('staff', '職員'), ('manager', '管理者')], default='user', max_length=20, verbose_name='権限種別'),
        ),
    ]
