# Generated by Django 5.2.3 on 2025-07-18 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_management', '0007_staff_role_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='日付')),
                ('name', models.CharField(max_length=100, verbose_name='祝日名')),
                ('holiday_type', models.CharField(choices=[('national', '国民の祝日'), ('company', '会社休日'), ('regional', '地域休日')], default='national', max_length=20, verbose_name='祝日種別')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': '祝日・休日',
                'verbose_name_plural': '祝日・休日',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('event_type', models.CharField(choices=[('meeting', '会議'), ('training', '研修'), ('event', 'イベント'), ('maintenance', 'メンテナンス'), ('other', 'その他')], max_length=50, verbose_name='イベント種別')),
                ('start_datetime', models.DateTimeField(verbose_name='開始日時')),
                ('end_datetime', models.DateTimeField(verbose_name='終了日時')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='場所')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': 'イベント',
                'verbose_name_plural': 'イベント',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('invited', '招待済み'), ('accepted', '参加'), ('declined', '不参加'), ('maybe', '未定')], default='invited', max_length=20, verbose_name='参加状況')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='招待日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_management.event', verbose_name='イベント')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_management.staff', verbose_name='スタッフ')),
            ],
            options={
                'verbose_name': 'イベント参加者',
                'verbose_name_plural': 'イベント参加者',
                'unique_together': {('event', 'staff')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(through='shift_management.EventParticipant', to='shift_management.staff', verbose_name='参加者'),
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('paid_leave', '有給休暇'), ('sick_leave', '病気休暇'), ('medical_appointment', '通院'), ('other', 'その他')], max_length=50, verbose_name='申請種別')),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('end_date', models.DateField(verbose_name='終了日')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='理由')),
                ('priority', models.CharField(choices=[('low', '通常'), ('medium', '重要'), ('high', '緊急')], default='low', max_length=20, verbose_name='緊急度')),
                ('approval_status', models.CharField(choices=[('pending', '承認待ち'), ('approved', '承認済み'), ('rejected', '却下')], default='pending', max_length=20, verbose_name='承認状態')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='承認日時')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='却下理由')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申請日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='承認者')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_management.staff', verbose_name='スタッフ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='申請者')),
            ],
            options={
                'verbose_name': '休み・通院申請',
                'verbose_name_plural': '休み・通院申請',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShiftProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField(verbose_name='シフト日')),
                ('start_time', models.TimeField(verbose_name='開始時間')),
                ('end_time', models.TimeField(verbose_name='終了時間')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='担当ポジション')),
                ('message', models.TextField(blank=True, null=True, verbose_name='メッセージ')),
                ('status', models.CharField(choices=[('pending', '回答待ち'), ('accepted', '承諾'), ('declined', '拒否'), ('expired', '期限切れ')], default='pending', max_length=20, verbose_name='回答状況')),
                ('response_deadline', models.DateTimeField(blank=True, null=True, verbose_name='回答期限')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='回答日時')),
                ('response_message', models.TextField(blank=True, null=True, verbose_name='回答メッセージ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='打診日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_proposals', to=settings.AUTH_USER_MODEL, verbose_name='打診者')),
                ('proposed_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_management.staff', verbose_name='打診先スタッフ')),
                ('shift_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shift_management.shifttype', verbose_name='シフト種別')),
            ],
            options={
                'verbose_name': 'シフト打診',
                'verbose_name_plural': 'シフト打診',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffCompatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compatibility_level', models.IntegerField(choices=[(1, '避ける'), (2, '注意'), (3, '普通'), (4, '良好')], verbose_name='相性レベル')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='設定理由')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='設定日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('set_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='設定者')),
                ('staff1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_as_staff1', to='shift_management.staff', verbose_name='スタッフ1')),
                ('staff2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_as_staff2', to='shift_management.staff', verbose_name='スタッフ2')),
            ],
            options={
                'verbose_name': 'スタッフ間相性設定',
                'verbose_name_plural': 'スタッフ間相性設定',
                'unique_together': {('staff1', 'staff2')},
            },
        ),
    ]
