# Generated by Django 5.2.3 on 2025-07-17 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_management', '0007_staff_role_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='組織名')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='組織コード')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('timezone', models.CharField(default='Asia/Tokyo', max_length=50, verbose_name='タイムゾーン')),
                ('currency', models.CharField(default='JPY', max_length=3, verbose_name='通貨')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='連絡先メール')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='連絡先電話')),
                ('address', models.TextField(blank=True, null=True, verbose_name='住所')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '組織',
                'verbose_name_plural': '組織',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['organization', 'name'], 'verbose_name': 'スタッフ', 'verbose_name_plural': 'スタッフ'},
        ),
        migrations.AddField(
            model_name='staff',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shift_management.organization', verbose_name='所属組織'),
        ),
        migrations.AddConstraint(
            model_name='staff',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False)), fields=('organization', 'email'), name='unique_email_per_organization'),
        ),
    ]
