# Generated by Django 5.2.3 on 2025-08-08 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_management', '0009_holiday_event_eventparticipant_event_participants_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50, unique=True, verbose_name='品目コード')),
                ('item_name', models.CharField(max_length=200, verbose_name='品目名')),
                ('unit', models.CharField(default='個', max_length=20, verbose_name='単位')),
                ('order_url', models.URLField(blank=True, null=True, verbose_name='発注先URL')),
                ('threshold', models.IntegerField(default=10, verbose_name='在庫閾値')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_management.organization', verbose_name='組織')),
            ],
            options={
                'verbose_name': '品目',
                'verbose_name_plural': '品目',
                'ordering': ['item_code'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_quantity', models.IntegerField(verbose_name='発注数量')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='発注日時')),
                ('supplier_url', models.URLField(blank=True, null=True, verbose_name='発注先URL')),
                ('status', models.CharField(choices=[('ordered', '発注済み'), ('delivered', '納品済み'), ('cancelled', 'キャンセル')], default='ordered', max_length=20, verbose_name='ステータス')),
                ('delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='納品日時')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_management.item', verbose_name='品目')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='発注担当者')),
            ],
            options={
                'verbose_name': '発注履歴',
                'verbose_name_plural': '発注履歴',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('in', '入庫'), ('out', '出庫'), ('adjustment', '在庫修正')], max_length=20, verbose_name='トランザクションタイプ')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('transaction_date', models.DateTimeField(auto_now_add=True, verbose_name='トランザクション日時')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_management.item', verbose_name='品目')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='担当者')),
            ],
            options={
                'verbose_name': '入出庫履歴',
                'verbose_name_plural': '入出庫履歴',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock', models.IntegerField(default=0, verbose_name='現在の在庫数')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='shift_management.item', verbose_name='品目')),
            ],
            options={
                'verbose_name': '在庫',
                'verbose_name_plural': '在庫',
                'unique_together': {('item',)},
            },
        ),
    ]
