# Generated by Django 5.2.3 on 2025-08-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_management', '0010_item_order_transaction_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_code',
            field=models.CharField(max_length=50, verbose_name='品目コード'),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('item_code', 'organization')},
        ),
    ]
