# Generated by Django 5.2.3 on 2025-08-08 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_management', '0011_alter_item_item_code_alter_item_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='inventory_permission',
            field=models.CharField(choices=[('none', '権限なし'), ('view', '閲覧のみ'), ('edit', '編集可能'), ('admin', '管理者権限')], default='none', max_length=20, verbose_name='在庫管理権限'),
        ),
        migrations.CreateModel(
            name='InventoryAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('item_create', '品目作成'), ('item_update', '品目更新'), ('item_delete', '品目削除'), ('inventory_in', '入庫処理'), ('inventory_out', '出庫処理'), ('inventory_adjust', '在庫修正'), ('order_create', '発注作成'), ('order_update', '発注更新'), ('order_cancel', '発注キャンセル'), ('user_login', 'ログイン'), ('user_logout', 'ログアウト'), ('permission_change', '権限変更')], max_length=20, verbose_name='操作種別')),
                ('target_model', models.CharField(blank=True, max_length=50, null=True, verbose_name='対象モデル')),
                ('target_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='対象オブジェクトID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='操作説明')),
                ('old_values', models.JSONField(blank=True, null=True, verbose_name='変更前データ')),
                ('new_values', models.JSONField(blank=True, null=True, verbose_name='変更後データ')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IPアドレス')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='ユーザーエージェント')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='実行日時')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_management.organization', verbose_name='組織')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='実行ユーザー')),
            ],
            options={
                'verbose_name': '監査ログ',
                'verbose_name_plural': '監査ログ',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['organization', '-timestamp'], name='shift_manag_organiz_75be19_idx'), models.Index(fields=['user', '-timestamp'], name='shift_manag_user_id_e1ba43_idx'), models.Index(fields=['action', '-timestamp'], name='shift_manag_action_1e2d01_idx')],
            },
        ),
    ]
