# Generated by Django 5.2.3 on 2025-08-12 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_management', '0012_staff_inventory_permission_inventoryauditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='請求書番号')),
                ('bill_to_name', models.CharField(max_length=200, verbose_name='請求先名')),
                ('bill_to_address', models.TextField(verbose_name='請求先住所')),
                ('bill_to_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='担当者')),
                ('bill_to_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='電話番号')),
                ('bill_to_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='メールアドレス')),
                ('issue_date', models.DateField(verbose_name='発行日')),
                ('due_date', models.DateField(verbose_name='支払期限')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='小計')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='消費税率(%)')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='消費税額')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='合計金額')),
                ('status', models.CharField(choices=[('draft', '下書き'), ('issued', '発行済み'), ('paid', '入金済み'), ('overdue', '支払期限超過'), ('cancelled', 'キャンセル')], default='draft', max_length=20, verbose_name='ステータス')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='入金日')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shift_management.order', verbose_name='関連発注')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_management.organization', verbose_name='組織')),
            ],
            options={
                'verbose_name': '請求書',
                'verbose_name_plural': '請求書',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_number', models.CharField(max_length=50, unique=True, verbose_name='納品書番号')),
                ('deliver_to_name', models.CharField(max_length=200, verbose_name='納品先名')),
                ('deliver_to_address', models.TextField(verbose_name='納品先住所')),
                ('deliver_to_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='担当者')),
                ('deliver_to_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='電話番号')),
                ('issue_date', models.DateField(verbose_name='発行日')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='納品予定日')),
                ('actual_delivery_date', models.DateField(blank=True, null=True, verbose_name='実際の納品日')),
                ('status', models.CharField(choices=[('draft', '下書き'), ('issued', '発行済み'), ('delivered', '納品済み'), ('cancelled', 'キャンセル')], default='draft', max_length=20, verbose_name='ステータス')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shift_management.invoice', verbose_name='関連請求書')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shift_management.order', verbose_name='関連発注')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_management.organization', verbose_name='組織')),
            ],
            options={
                'verbose_name': '納品書',
                'verbose_name_plural': '納品書',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, verbose_name='品目名')),
                ('item_description', models.TextField(blank=True, null=True, verbose_name='品目説明')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='数量')),
                ('unit', models.CharField(default='個', max_length=20, verbose_name='単位')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='単価')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金額')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shift_management.invoice', verbose_name='請求書')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shift_management.item', verbose_name='品目')),
            ],
            options={
                'verbose_name': '請求書明細',
                'verbose_name_plural': '請求書明細',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, verbose_name='品目名')),
                ('item_description', models.TextField(blank=True, null=True, verbose_name='品目説明')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='数量')),
                ('unit', models.CharField(default='個', max_length=20, verbose_name='単位')),
                ('delivered_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='実際の納品数量')),
                ('delivery_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shift_management.deliverynote', verbose_name='納品書')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shift_management.item', verbose_name='品目')),
            ],
            options={
                'verbose_name': '納品書明細',
                'verbose_name_plural': '納品書明細',
                'ordering': ['id'],
            },
        ),
    ]