# Generated by Django 5.2.3 on 2025-11-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_management', '0015_invoice_deliverynote_issuer_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='company_logo',
            field=models.ImageField(blank=True, help_text='請求書・納品書に表示される会社ロゴ画像', null=True, upload_to='organization/logos/', verbose_name='会社ロゴ'),
        ),
        migrations.AddField(
            model_name='organization',
            name='company_seal',
            field=models.ImageField(blank=True, help_text='請求書・納品書に表示される会社印画像', null=True, upload_to='organization/seals/', verbose_name='会社印'),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='status',
            field=models.CharField(choices=[('draft', '下書き'), ('issued', '発行済み'), ('delivered', '納品済み'), ('cancelled', 'キャンセル')], default='draft', max_length=20, verbose_name='状態'),
        ),
        migrations.AlterField(
            model_name='inventoryauditlog',
            name='action',
            field=models.CharField(choices=[('item_create', '品目作成'), ('item_update', '品目更新'), ('item_delete', '品目削除'), ('inventory_in', '入庫処理'), ('inventory_out', '出庫処理'), ('inventory_adjust', '在庫修正'), ('order_create', '発注作成'), ('order_update', '発注更新'), ('order_cancel', '発注キャンセル'), ('invoice_create', '請求書作成'), ('invoice_update', '請求書更新'), ('invoice_status', '請求書ステータス変更'), ('delivery_note_create', '納品書作成'), ('delivery_note_status', '納品書ステータス変更'), ('user_login', 'ログイン'), ('user_logout', 'ログアウト'), ('permission_change', '権限変更')], max_length=20, verbose_name='操作種別'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', '下書き'), ('issued', '発行済み'), ('paid', '入金済み'), ('overdue', '支払期限超過'), ('cancelled', 'キャンセル')], default='draft', max_length=20, verbose_name='状態'),
        ),
        migrations.AlterField(
            model_name='item',
            name='threshold',
            field=models.IntegerField(default=10, help_text='この数を下回ると不足として表示されます', verbose_name='在庫の目安数'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ordered', '発注済み'), ('delivered', '納品済み'), ('cancelled', 'キャンセル')], default='ordered', max_length=20, verbose_name='状態'),
        ),
    ]
