# Generated by Django 5.2.3 on 2025-11-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_management', '0016_organization_company_logo_organization_company_seal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role_type',
            field=models.CharField(choices=[('user', '利用者'), ('part_time', 'アルバイト'), ('staff', '職員'), ('manager', '管理者'), ('global_admin', 'グローバル管理者')], default='user', max_length=20, verbose_name='権限種別'),
        ),
    ]
