# Generated by Django 5.2.3 on 2025-11-17 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shift_management', '0016_alter_deliverynote_status_and_more'),
        ('shift_management', '0016_organization_company_logo_organization_company_seal_and_more'),
    ]

    operations = [
    ]
