# Generated by Django 5.2.3 on 2025-11-19 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_management', '0017_add_global_admin_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifttemplate',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shift_management.organization', verbose_name='組織'),
        ),
    ]
