# Generated by Django 5.2.3 on 2025-11-25 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_management', '0018_add_organization_to_shift_template'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shifttemplatedetail',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='shifttemplatedetail',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shift_management.staff', verbose_name='スタッフ'),
        ),
    ]
