# Generated by Django 5.2.3 on 2025-06-26 03:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CultivationLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='レイアウト名')),
                ('layout_image', models.ImageField(blank=True, null=True, upload_to='layouts/', verbose_name='レイアウト図')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
            ],
        ),
        migrations.CreateModel(
            name='CultivationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100, verbose_name='作物名')),
                ('sowing_date', models.DateField(blank=True, null=True, verbose_name='播種日')),
                ('planting_date', models.DateField(blank=True, null=True, verbose_name='定植日')),
                ('harvest_date_actual', models.DateField(blank=True, null=True, verbose_name='収穫日')),
                ('harvest_date_planned', models.DateField(blank=True, null=True, verbose_name='収穫予定日')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='メモ')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
            ],
        ),
        migrations.CreateModel(
            name='CultivationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='記録日')),
                ('status', models.CharField(choices=[('sowing', '播種'), ('germination', '発芽'), ('planting', '定植'), ('growing', '成長'), ('harvested', '収穫')], max_length=20, verbose_name='生育段階')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='メモ')),
                ('log_image', models.ImageField(blank=True, null=True, upload_to='logs/', verbose_name='写真')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='cultivation.cultivationplan', verbose_name='栽培計画')),
            ],
        ),
        migrations.CreateModel(
            name='CultivationSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='区画名')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='cultivation.cultivationlayout', verbose_name='レイアウト')),
            ],
        ),
        migrations.AddField(
            model_name='cultivationplan',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='cultivation.cultivationsection', verbose_name='区画'),
        ),
    ]
