# Generated by Django 5.2.3 on 2025-06-26 04:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='作物名')),
                ('color', models.CharField(default='#808080', help_text='例: #FFFFFF', max_length=7, verbose_name='色コード')),
            ],
        ),
        migrations.AlterModelOptions(
            name='cultivationsection',
            options={'ordering': ['row', 'column']},
        ),
        migrations.RemoveField(
            model_name='cultivationplan',
            name='crop_name',
        ),
        migrations.AddField(
            model_name='cultivationsection',
            name='column',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='列番号'),
        ),
        migrations.AddField(
            model_name='cultivationsection',
            name='row',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='行番号'),
        ),
        migrations.AlterUniqueTogether(
            name='cultivationsection',
            unique_together={('layout', 'row', 'column')},
        ),
        migrations.AddField(
            model_name='cultivationplan',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cultivation.crop', verbose_name='作物'),
        ),
    ]
