# Generated by Django 5.2.3 on 2025-06-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivation', '0002_crop_alter_cultivationsection_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivationlayout',
            name='import_file',
            field=models.FileField(blank=True, help_text='PDF、Excel、画像ファイルをアップロードして自動的にレイアウトを作成', null=True, upload_to='imports/', verbose_name='インポートファイル'),
        ),
    ]
