# Generated by Django 5.2.3 on 2025-07-01 03:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivation', '0003_cultivationlayout_import_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf_number', models.CharField(max_length=20, unique=True, verbose_name='棚番号')),
                ('x_position', models.PositiveIntegerField(help_text='グリッド表示時の横位置', verbose_name='X座標')),
                ('y_position', models.PositiveIntegerField(help_text='グリッド表示時の縦位置', verbose_name='Y座標')),
                ('levels', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='段数')),
            ],
            options={
                'verbose_name': '棚区画',
                'verbose_name_plural': '棚区画',
                'ordering': ['y_position', 'x_position'],
                'unique_together': {('x_position', 'y_position')},
            },
        ),
        migrations.CreateModel(
            name='ShelfCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety', models.CharField(max_length=100, verbose_name='品種')),
                ('planting_date', models.DateField(verbose_name='植付日')),
                ('expected_harvest_date', models.DateField(verbose_name='収穫予定日')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelf_crops', to='cultivation.plot', verbose_name='棚区画')),
            ],
            options={
                'verbose_name': '棚栽培作物',
                'verbose_name_plural': '棚栽培作物',
                'ordering': ['-planting_date'],
            },
        ),
        migrations.CreateModel(
            name='CropImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='crop_images/%Y/%m/%d/', verbose_name='画像')),
                ('capture_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='撮影日時')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='アップロード日時')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cultivation.shelfcrop', verbose_name='作物')),
            ],
            options={
                'verbose_name': '作物画像',
                'verbose_name_plural': '作物画像',
                'ordering': ['-capture_date'],
            },
        ),
    ]
