# Generated by Django 5.2.3 on 2025-07-24 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivation', '0004_plot_shelfcrop_cropimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='base_height',
            field=models.FloatField(default=0.8, help_text='床からの基本高さ（メートル）', validators=[django.core.validators.MinValueValidator(0)], verbose_name='基底高さ(m)'),
        ),
        migrations.AddField(
            model_name='plot',
            name='depth',
            field=models.FloatField(default=0.5, help_text='実際の棚の奥行（メートル）', validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='奥行(m)'),
        ),
        migrations.AddField(
            model_name='plot',
            name='height_per_level',
            field=models.FloatField(default=0.5, help_text='各段の高さ間隔（メートル）', validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='段間隔(m)'),
        ),
        migrations.AddField(
            model_name='plot',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='使用中'),
        ),
        migrations.AddField(
            model_name='plot',
            name='maintenance_notes',
            field=models.TextField(blank=True, null=True, verbose_name='メンテナンス備考'),
        ),
        migrations.AddField(
            model_name='plot',
            name='width',
            field=models.FloatField(default=1.0, help_text='実際の棚の幅（メートル）', validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='幅(m)'),
        ),
        migrations.AddField(
            model_name='shelfcrop',
            name='level',
            field=models.PositiveIntegerField(default=1, help_text='棚の何段目か', validators=[django.core.validators.MinValueValidator(1)], verbose_name='段数'),
        ),
    ]
