# Generated by Django 5.2.3 on 2025-07-29 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivation', '0005_plot_base_height_plot_depth_plot_height_per_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='cultivation.cultivationlayout', verbose_name='レイアウト'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='shelf_number',
            field=models.CharField(max_length=20, verbose_name='棚番号'),
        ),
    ]
