# Generated by Django 5.2.3 on 2025-07-29 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cultivation', '0006_plot_layout_alter_plot_shelf_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plot',
            unique_together={('layout', 'x_position', 'y_position')},
        ),
    ]
