# Generated by Django 5.2.3 on 2025-07-30 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivation', '0007_alter_plot_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='svg_x',
            field=models.FloatField(default=100.0, help_text='2D平面図でのX座標', verbose_name='SVG X座標'),
        ),
        migrations.AddField(
            model_name='plot',
            name='svg_y',
            field=models.FloatField(default=100.0, help_text='2D平面図でのY座標', verbose_name='SVG Y座標'),
        ),
    ]
