# Generated by Django 5.2.3 on 2025-07-30 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivation', '0008_plot_svg_x_plot_svg_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='section',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plot', to='cultivation.cultivationsection', verbose_name='対応区画'),
        ),
    ]
