# Generated by Django 5.2.3 on 2025-07-30 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivation', '0009_plot_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='threejs_x',
            field=models.FloatField(default=0.0, help_text='3D表示でのX座標（メートル単位）', verbose_name='3D X座標'),
        ),
        migrations.AddField(
            model_name='plot',
            name='threejs_y',
            field=models.FloatField(default=0.0, help_text='3D表示でのY座標（高さ、メートル単位）', verbose_name='3D Y座標'),
        ),
        migrations.AddField(
            model_name='plot',
            name='threejs_z',
            field=models.FloatField(default=0.0, help_text='3D表示でのZ座標（奥行、メートル単位）', verbose_name='3D Z座標'),
        ),
    ]
