# Generated by Django 5.2.3 on 2025-07-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivation', '0010_plot_threejs_x_plot_threejs_y_plot_threejs_z'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelfcrop',
            name='harvest_date',
            field=models.DateField(blank=True, null=True, verbose_name='収穫日'),
        ),
    ]
