# Generated by Django 5.2.3 on 2025-11-19 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivation', '0011_shelfcrop_harvest_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='工程名')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='工程コード')),
                ('color', models.CharField(default='#808080', help_text='例: #4CAF50', max_length=7, verbose_name='表示色')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
            ],
            options={
                'verbose_name': '栽培工程',
                'verbose_name_plural': '栽培工程',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='CropTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='テンプレート名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('is_default', models.BooleanField(default=False, verbose_name='デフォルト')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='cultivation.crop', verbose_name='作物')),
            ],
            options={
                'verbose_name': '栽培テンプレート',
                'verbose_name_plural': '栽培テンプレート',
                'unique_together': {('crop', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CropTemplateProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_days', models.PositiveIntegerField(verbose_name='標準日数')),
                ('start_offset_days', models.PositiveIntegerField(default=0, verbose_name='開始オフセット日数')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivation.cropprocess', verbose_name='工程')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='cultivation.croptemplate', verbose_name='テンプレート')),
            ],
            options={
                'verbose_name': 'テンプレート工程',
                'verbose_name_plural': 'テンプレート工程',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='CultivationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('end_date', models.DateField(verbose_name='終了日')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('is_completed', models.BooleanField(default=False, verbose_name='完了')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='完了日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivation.cropprocess', verbose_name='工程')),
                ('shelf_crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='cultivation.shelfcrop', verbose_name='棚作物')),
            ],
            options={
                'verbose_name': '栽培スケジュール',
                'verbose_name_plural': '栽培スケジュール',
                'ordering': ['start_date', 'process__display_order'],
            },
        ),
    ]
