# Generated by Django 5.2.3 on 2025-11-19 04:31

from django.db import migrations


def add_initial_processes(apps, schema_editor):
    """基本的な栽培工程マスターを追加"""
    CropProcess = apps.get_model('cultivation', 'CropProcess')

    processes = [
        {
            'name': '播種',
            'code': 'seeding',
            'color': '#4CAF50',
            'display_order': 1,
            'description': '種まき工程'
        },
        {
            'name': '発芽',
            'code': 'germination',
            'color': '#8BC34A',
            'display_order': 2,
            'description': '発芽工程'
        },
        {
            'name': '定植',
            'code': 'planting',
            'color': '#2196F3',
            'display_order': 3,
            'description': '苗を植え替える工程'
        },
        {
            'name': '栽培',
            'code': 'growing',
            'color': '#03A9F4',
            'display_order': 4,
            'description': '成長期間'
        },
        {
            'name': '日光管理',
            'code': 'light_management',
            'color': '#FFC107',
            'display_order': 5,
            'description': '日光を当てる工程'
        },
        {
            'name': '収穫期',
            'code': 'harvest_ready',
            'color': '#FF9800',
            'display_order': 6,
            'description': '収穫可能な期間'
        },
        {
            'name': '収穫済み',
            'code': 'harvested',
            'color': '#9E9E9E',
            'display_order': 7,
            'description': '収穫完了'
        },
    ]

    for process_data in processes:
        CropProcess.objects.get_or_create(
            code=process_data['code'],
            defaults=process_data
        )


def remove_initial_processes(apps, schema_editor):
    """初期工程データを削除（ロールバック用）"""
    CropProcess = apps.get_model('cultivation', 'CropProcess')

    process_codes = [
        'seeding', 'germination', 'planting', 'growing',
        'light_management', 'harvest_ready', 'harvested'
    ]

    CropProcess.objects.filter(code__in=process_codes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cultivation', '0012_cropprocess_croptemplate_croptemplateprocess_and_more'),
    ]

    operations = [
        migrations.RunPython(add_initial_processes, remove_initial_processes),
    ]
