# Generated by Django 5.2.3 on 2025-11-19 11:30

import django.db.models.deletion
from django.db import migrations, models


def assign_default_organization(apps, schema_editor):
    """既存データに最初の組織を割り当てる"""
    Organization = apps.get_model('shift_management', 'Organization')
    CultivationLayout = apps.get_model('cultivation', 'CultivationLayout')
    Plot = apps.get_model('cultivation', 'Plot')
    ShelfCrop = apps.get_model('cultivation', 'ShelfCrop')

    # 最初の組織を取得（通常は「わかくさ」）
    try:
        default_org = Organization.objects.filter(is_active=True).first()
        if default_org:
            # 既存のCultivationLayoutに組織を割り当て
            CultivationLayout.objects.filter(organization__isnull=True).update(organization=default_org)

            # 既存のPlotに組織を割り当て
            Plot.objects.filter(organization__isnull=True).update(organization=default_org)

            # 既存のShelfCropに組織を割り当て
            ShelfCrop.objects.filter(organization__isnull=True).update(organization=default_org)

            print(f"既存の栽培データを組織「{default_org.name}」に割り当てました。")
    except Exception as e:
        print(f"組織割り当て中にエラー: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ('cultivation', '0013_add_initial_crop_processes'),
        ('shift_management', '0018_add_organization_to_shift_template'),
    ]

    operations = [
        # Step 1: 古いunique_togetherを削除
        migrations.AlterUniqueTogether(
            name='plot',
            unique_together=set(),
        ),
        # Step 2: organizationフィールドを追加
        migrations.AddField(
            model_name='cultivationlayout',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cultivation_layouts', to='shift_management.organization', verbose_name='組織'),
        ),
        migrations.AddField(
            model_name='plot',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='shift_management.organization', verbose_name='組織'),
        ),
        migrations.AddField(
            model_name='shelfcrop',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shelf_crops', to='shift_management.organization', verbose_name='組織'),
        ),
        # Step 3: 既存データに組織を割り当て
        migrations.RunPython(assign_default_organization, migrations.RunPython.noop),
        # Step 4: 新しいunique_togetherを設定（組織フィールドを含む）
        migrations.AlterUniqueTogether(
            name='cultivationlayout',
            unique_together={('name', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='plot',
            unique_together={('layout', 'x_position', 'y_position')},  # shelf_numberの制約は後で手動で追加
        ),
    ]
