# Generated by Django 5.2.3 on 2025-12-17 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivation', '0014_alter_plot_unique_together_and_more'),
        ('shift_management', '0019_alter_shifttemplatedetail_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropprocess',
            name='default_duration',
            field=models.PositiveIntegerField(default=7, help_text='日数', verbose_name='デフォルト期間'),
        ),
        migrations.AddField(
            model_name='cropprocess',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='有効'),
        ),
        migrations.AddField(
            model_name='cropprocess',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='nullの場合は全組織共通', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crop_processes', to='shift_management.organization', verbose_name='組織'),
        ),
        migrations.AlterField(
            model_name='cropprocess',
            name='code',
            field=models.CharField(max_length=20, verbose_name='工程コード'),
        ),
        migrations.AlterUniqueTogether(
            name='cropprocess',
            unique_together={('organization', 'code')},
        ),
        migrations.CreateModel(
            name='HolidayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunday_off', models.BooleanField(default=True, verbose_name='日曜休み')),
                ('monday_off', models.BooleanField(default=False, verbose_name='月曜休み')),
                ('tuesday_off', models.BooleanField(default=False, verbose_name='火曜休み')),
                ('wednesday_off', models.BooleanField(default=False, verbose_name='水曜休み')),
                ('thursday_off', models.BooleanField(default=False, verbose_name='木曜休み')),
                ('friday_off', models.BooleanField(default=False, verbose_name='金曜休み')),
                ('saturday_off', models.BooleanField(default=True, verbose_name='土曜休み')),
                ('skip_holidays', models.BooleanField(default=False, help_text='工程期間計算時に休日を除外するか', verbose_name='休日スキップ')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_config', to='shift_management.organization', verbose_name='組織')),
            ],
            options={
                'verbose_name': '休日設定',
                'verbose_name_plural': '休日設定',
            },
        ),
        migrations.CreateModel(
            name='ProcessSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(blank=True, help_text='nullなら棚全体', null=True, verbose_name='段')),
                ('group_name', models.CharField(blank=True, help_text='任意のグループ名', max_length=100, verbose_name='グループ名')),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('end_date', models.DateField(verbose_name='終了日')),
                ('is_linked', models.BooleanField(default=True, help_text='前後の工程と連携して移動するか', verbose_name='連携有効')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_schedules', to='shift_management.organization', verbose_name='組織')),
                ('parent_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_schedules', to='cultivation.processschedule', verbose_name='親スケジュール')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_schedules', to='cultivation.plot', verbose_name='棚')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_schedules', to='cultivation.cropprocess', verbose_name='工程')),
            ],
            options={
                'verbose_name': '工程スケジュール',
                'verbose_name_plural': '工程スケジュール',
                'ordering': ['plot', 'level', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('name', models.CharField(blank=True, help_text='祝日名など', max_length=100, verbose_name='名称')),
                ('holiday_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='cultivation.holidayconfig', verbose_name='休日設定')),
            ],
            options={
                'verbose_name': '個別休日',
                'verbose_name_plural': '個別休日',
                'ordering': ['date'],
                'unique_together': {('holiday_config', 'date')},
            },
        ),
        migrations.CreateModel(
            name='LaneConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(blank=True, help_text='nullなら棚全体のデフォルト', null=True, verbose_name='段')),
                ('max_overlap', models.PositiveIntegerField(default=1, help_text='1=重ね禁止', verbose_name='最大重ね本数')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lane_configs', to='shift_management.organization', verbose_name='組織')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lane_configs', to='cultivation.plot', verbose_name='棚')),
            ],
            options={
                'verbose_name': 'レーン設定',
                'verbose_name_plural': 'レーン設定',
                'unique_together': {('organization', 'plot', 'level')},
            },
        ),
    ]
