# Generated by Django 5.2.3 on 2026-05-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivation', '0015_add_gantt_chart_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='max_plates',
            field=models.PositiveIntegerField(default=14, help_text='このレーン（棚）に入れられるプレートの最大枚数（例: 14枚 or 8枚）', verbose_name='最大プレート数'),
        ),
        migrations.AddField(
            model_name='shelfcrop',
            name='plate_count',
            field=models.PositiveIntegerField(default=0, help_text='このレーン・段に入れているプレートの枚数', verbose_name='プレート数'),
        ),
        migrations.AddField(
            model_name='shelfcrop',
            name='pre_planting_date',
            field=models.DateField(blank=True, null=True, verbose_name='仮植日'),
        ),
        migrations.AddField(
            model_name='shelfcrop',
            name='sowing_date',
            field=models.DateField(blank=True, null=True, verbose_name='播種日'),
        ),
        migrations.AlterField(
            model_name='shelfcrop',
            name='expected_harvest_date',
            field=models.DateField(blank=True, null=True, verbose_name='収穫予定日'),
        ),
        migrations.AlterField(
            model_name='shelfcrop',
            name='planting_date',
            field=models.DateField(blank=True, null=True, verbose_name='定植日'),
        ),
    ]
